# Generated by Django 4.1.7 on 2023-02-23 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_tag_product_category_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('hearts', models.IntegerField(choices=[(1, '❤️'), (2, '❤️❤️'), (3, '❤️❤️❤️'), (4, '❤️❤️❤️❤️'), (5, '❤️❤️❤️❤️❤️')], default=5)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='store.product')),
            ],
        ),
    ]
